GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/6a42801fac78f271314ee154

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

 {
    "name": "Josefina",
    "number": "321-98547-996"
  }

###
DELETE http://localhost:3001/api/persons/4